package provider

import "testing"

// The size map is parsed at init from the embedded catalog.json artifact
// (schema shc-catalog/1, generated by shc-toolkit's
// scripts/generate-catalog-json.py). These tests pin that hand-off: the
// artifact parses, carries the expected shape, and the derived map agrees
// with known catalog values.

func TestCatalogArtifactParses(t *testing.T) {
	if catalogArtifact.Schema != "shc-catalog/1" {
		t.Errorf("embedded catalog schema = %q, want shc-catalog/1", catalogArtifact.Schema)
	}
	if catalogArtifact.APIVersion == "" || catalogArtifact.ToolkitVersion == "" {
		t.Error("embedded catalog is missing api_version/toolkit_version")
	}
}

func TestSizeMapDerivedFromCatalog(t *testing.T) {
	if len(sizeMap) != 20 {
		t.Fatalf("size map has %d entries, want 20", len(sizeMap))
	}
	s, ok := sizeMap["dev-1c-4gb"]
	if !ok {
		t.Fatal("dev-1c-4gb missing from size map")
	}
	if s.PackageID != 80 || s.PricingID != 241 || s.Line != "dev" {
		t.Errorf("dev-1c-4gb = %+v, want package 80 / pricing 241 / line dev", s)
	}
	if s.DailyPrice != 0.24 {
		t.Errorf("dev-1c-4gb daily price = %v, want 0.24", s.DailyPrice)
	}
}
